# Generated by Django 4.2.4 on 2023-08-24 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
